export enum LikeStatus {
  DISLIKE = 'DISLIKE',
  INDIFFERENT = 'INDIFFERENT',
  LIKE = 'LIKE'
}

export enum MediaFormatQualityOrdinal {
  QUALITY_ORDINAL_UNKNOWN = 'QUALITY_ORDINAL_UNKNOWN',
  QUALITY_ORDINAL_144P = 'QUALITY_ORDINAL_144P',
  QUALITY_ORDINAL_240P = 'QUALITY_ORDINAL_240P',
  QUALITY_ORDINAL_240P_SAVER = 'QUALITY_ORDINAL_240P_SAVER',
  QUALITY_ORDINAL_360P = 'QUALITY_ORDINAL_360P',
  QUALITY_ORDINAL_360P_SAVER = 'QUALITY_ORDINAL_360P_SAVER',
  QUALITY_ORDINAL_480P = 'QUALITY_ORDINAL_480P',
  QUALITY_ORDINAL_608P = 'QUALITY_ORDINAL_608P',
  QUALITY_ORDINAL_608P_SAVER = 'QUALITY_ORDINAL_608P_SAVER',
  QUALITY_ORDINAL_720P = 'QUALITY_ORDINAL_720P',
  QUALITY_ORDINAL_1080P = 'QUALITY_ORDINAL_1080P',
  QUALITY_ORDINAL_1080P_ENHANCED = 'QUALITY_ORDINAL_1080P_ENHANCED',
  QUALITY_ORDINAL_1440P = 'QUALITY_ORDINAL_1440P',
  QUALITY_ORDINAL_2160P = 'QUALITY_ORDINAL_2160P'
}

export enum MusicVideoType {
  MUSIC_VIDEO_TYPE_ATV = 'MUSIC_VIDEO_TYPE_ATV',
  MUSIC_VIDEO_TYPE_OFFICIAL_SOURCE_MUSIC = 'MUSIC_VIDEO_TYPE_OFFICIAL_SOURCE_MUSIC',
  MUSIC_VIDEO_TYPE_OMV = 'MUSIC_VIDEO_TYPE_OMV',
  MUSIC_VIDEO_TYPE_UGC = 'MUSIC_VIDEO_TYPE_UGC'
}

export enum OfflineFormatType {
  UNKNOWN_FORMAT_TYPE = 'UNKNOWN_FORMAT_TYPE',
  HD = 'HD',
  HD_1080 = 'HD_1080',
  LD = 'LD',
  SD = 'SD'
}