export const enum CompressionType {
  NONE = 0,
  GZIP = 1,
  BROTLI = 2
}

export const enum OnesieHeaderType {
  PLAYER_RESPONSE = 0,
  MEDIA = 1,
  MEDIA_DECRYPTION_KEY = 2,
  CLEAR_MEDIA = 3,
  CLEAR_INIT_SEGMENT = 4,
  ACK = 5,
  MEDIA_STREAMER_HOSTNAME = 6,
  MEDIA_SIZE_HINT = 7,
  PLAYER_SERVICE_RESPONSE_PUSH_URL = 8,
  LAST_HIGH_PRIORITY_HINT = 9,
  STREAM_METADATA = 16,
  ENCRYPTED_INNERTUBE_RESPONSE_PART = 25
}

export const enum OnesieProxyStatus {
  UNKNOWN = 0,
  OK = 1,
  DECRYPTION_FAILED = 2,
  PARSING_FAILED = 3,
  MISSING_X_FORWARDED_FOR = 4,
  INVALID_X_FORWARDED_FOR = 5,
  INVALID_CONTENT_TYPE = 6,
  BACKEND_ERROR = 7,
  CLIENT_ERROR = 8,
  MISSING_CRYPTER = 9,
  RESPONSE_JSON_SERIALIZATION_FAILED = 10,
  DECOMPRESSION_FAILED = 11,
  JSON_PARSING_FAILED = 12,
  UNKNOWN_COMPRESSION_TYPE = 13
}

export const enum SabrContextScope {
  SABR_CONTEXT_SCOPE_UNKNOWN = 0,
  SABR_CONTEXT_SCOPE_PLAYBACK = 1,
  SABR_CONTEXT_SCOPE_REQUEST = 2,
  SABR_CONTEXT_SCOPE_WATCH_ENDPOINT = 3,
  SABR_CONTEXT_SCOPE_CONTENT_ADS = 4
}

export const enum SabrContextWritePolicy {
  SABR_CONTEXT_WRITE_POLICY_UNSPECIFIED = 0,
  SABR_CONTEXT_WRITE_POLICY_OVERWRITE = 1,
  SABR_CONTEXT_WRITE_POLICY_KEEP_EXISTING = 2
}

export const enum UMPSliceType {
  UNKNOWN = 0,
  ONESIE_HEADER = 10,
  ONESIE_DATA = 11,
  ONESIE_ENCRYPTED_MEDIA = 12,
  MEDIA_HEADER = 20,
  MEDIA = 21,
  MEDIA_END = 22,
  CONFIG = 30,
  LIVE_METADATA = 31,
  HOSTNAME_CHANGE_HINT = 32,
  LIVE_METADATA_PROMISE = 33,
  LIVE_METADATA_PROMISE_CANCELLATION = 34,
  NEXT_REQUEST_POLICY = 35,
  USTREAMER_VIDEO_AND_FORMAT_DATA = 36,
  FORMAT_SELECTION_CONFIG = 37,
  USTREAMER_SELECTED_MEDIA_STREAM = 38,
  FORMAT_INITIALIZATION_METADATA = 42,
  SABR_REDIRECT = 43,
  SABR_ERROR = 44,
  SABR_SEEK = 45,
  RELOAD_PLAYER_RESPONSE = 46,
  PLAYBACK_START_POLICY = 47,
  ALLOWED_CACHED_FORMATS = 48,
  START_BW_SAMPLING_HINT = 49,
  PAUSE_BW_SAMPLING_HINT = 50,
  SELECTABLE_FORMATS = 51,
  REQUEST_IDENTIFIER = 52,
  REQUEST_CANCELLATION_POLICY = 53,
  ONESIE_PREFETCH_REJECTION = 54,
  TIMELINE_CONTEXT = 55,
  REQUEST_PIPELINING = 56,
  SABR_CONTEXT_UPDATE = 57,
  STREAM_PROTECTION_STATUS = 58,
  SABR_CONTEXT_SENDING_POLICY = 59,
  LAWNMOWER_POLICY = 60,
  SABR_ACK = 61,
  END_OF_TRACK = 62,
  CACHE_LOAD_POLICY = 63,
  LAWNMOWER_MESSAGING_POLICY = 64,
  PREWARM_CONNECTION = 65,
  PLAYBACK_DEBUG_INFO = 66,
  SNACKBAR_MESSAGE = 67
}