export const enum BURemoteCmd {
  CMD_STREAM_ID,
  CMD_SYNC_TIME_REQ,
  CMD_SYNC_TIME_RSP,
  CMD_IMPORT_REQ,
  CMD_IMPORT_RSP,
  CMD_EXPORT_REQ,
  CMD_EXPORT_RSP,
  CMD_PLAYER_INFO,
  CMD_PLAY,
  CMD_PAUSE,
  CMD_RELATIVE_SEEK,
  CMD_ABSOLUTE_SEEK,
  CMD_RELATIVE_VOLUME,
  CMD_ABSOLUTE_VOLUME
}
