import { bufferFromString, bufferToString } from '@ext/lib/buffer'
import { pbf_bol, pbf_i32, pbf_str } from '@ext/lib/protobuf/field'
import { createMessage } from '@ext/lib/protobuf/message'

export enum EntityType {
  accountLinkStatusEntity = 122,
  booleanEntity = 307,
  buttonEntity = 358,
  captionTrack = 225,
  channelHandle = 275,
  chipEntity = 498,
  commerceAcquisitionClientPayloadEntity = 276,
  commerceCartListEntity = 236,
  contextNoteFeedEntityPayload = 483,
  contextNoteUserRatingEntityPayload = 576,
  continuationTokenEntity = 406,
  downloadQualityPickerEntity = 202,
  downloadsPageRefreshTokenEntity = 299,
  downloadsPageViewConfigurationEntity = 264,
  downloadStatusEntity = 141,
  dismissState = 540,
  sfvAudioItemCurrentlyPlayingEntity = 186,
  emojiFountainDataEntity = 393,
  emojiCustomizationSetEntity = 496,
  fakeChannel = 2,
  fakePlaylist = 279,
  fakePlaylistEntryCollection = 280,
  fakeVideo = 182,
  fakeVideoDescription = 278,
  featuredProductsEntity = 392,
  flowStateEntity = 252,
  iconBadgeEntity = 229,
  interstitialInteractionStateEntity = 443,
  likeButtonAnimationEntity = 567,
  liveChatPollStateEntity = 217,
  liveViewerLeaderboardChatEntryPointStateEntity = 563,
  liveViewerLeaderboardPointsEntity = 564,
  liveReactionsDataEntity = 503,
  logoEntity = 245,
  macroMarkerEntity = 329,
  mainDownloadsLibraryEntity = 158,
  mainDownloadsListEntity = 164,
  mainPlaylistDownloadStateEntity = 373,
  mainPlaylistEntity = 306,
  mainPlaylistVideoEntity = 368,
  mainVideoDownloadStateEntity = 262,
  mainVideoEntity = 261,
  markersEngagementPanelSyncEntity = 196,
  markersVisibilityOverrideEntity = 312,
  musicAlbumReleaseDetail = 18,
  musicAlbumReleaseDownloadMetadataEntity = 259,
  musicAlbumRelease = 17,
  musicAlbumReleaseUserDetail = 19,
  musicArtistDetail = 21,
  musicArtist = 20,
  musicArtistUserDetail = 22,
  musicDownloadsLibraryEntity = 257,
  musicLibraryEdit = 121,
  musicLibraryStatusEntity = 318,
  musicPlaylist = 24,
  musicPlaylistDownloadMetadataEntity = 248,
  musicShare = 100,
  musicTrackDetail = 29,
  musicTrackDownloadMetadataEntity = 234,
  musicTrack = 28,
  musicTrackUserDetail = 30,
  offlineOrchestrationActionWrapperEntity = 169,
  offlineVideoPolicy = 130,
  offlineVideoStreams = 198,
  offlineabilityEntity = 246,
  orchestrationWebSamplingEntity = 242,
  pageHeaderEntity = 495,
  pdpStateEntity = 524,
  pinnedProductEntity = 273,
  playbackData = 119,
  quantityIncrementerEntity = 356,
  playerStateEntity = 323,
  refresh = 148,
  saveToPlaylistListEntity = 231,
  selectedChipIndexEntityPayload = 479,
  settingEntity = 297,
  stringEntity = 382,
  suggestedFeedbackChipStateEntity = 485,
  transfer = 120,
  trendingOfferEntity = 469,
  videoDownloadContextEntity = 461,
  videoOverviewAsyncDataEntity = 545,
  videoPlaybackPositionEntity = 76,
  votingEntity = 561,
  ytMainChannelEntity = 152,
  youchatPendingResponseEntity = 553,
  ytMainDownloadedVideoEntity = 155,
  ytMainVideoEntity = 151
}

const EntityKey = createMessage({
  entityId: pbf_str(2),
  entityType: pbf_i32(4),
  isPersistent: pbf_bol(5)
})

export const encodeEntityKey = (...args: ConstructorParameters<typeof EntityKey>): string => {
  return encodeURIComponent(btoa(bufferToString(new EntityKey(...args).serialize(), 'latin1')))
}

export const decodeEntityKey = (entityKey: string): InstanceType<typeof EntityKey> => {
  return new EntityKey().deserialize(bufferFromString(atob(decodeURIComponent(entityKey)), 'latin1'))
}

export default EntityKey